- src/main.rs
Minor side benefit: Format can now automatically derive Debug!
> Use a concrete type for functions instead of Rust closures

- Cargo.lock
- Cargo.toml
- rustfmt.toml
- src/byte_set.rs
- src/main.rs
This uses a specialised byte set as opposed to a `HashSet`. I'm wasn’t confident on some of the set operations, so added some property-based tests – but I can remove them we want to avoid adding a dependency at the moment.
> Use a non-allocating byte set

- Cargo.lock
- Cargo.toml
- src/main.rs
This lets us render decoded values as a JSON object. We might want to alter the schema later, just using the default [serde](https://serde.rs/) options at the moment. To actually work with the output values in a nicer way we might also want to output the format as a JSON object, along with the byte ranges for each node in the decoded values.
> Initial support for JSON output

- src/main.rs
This was useful as I was starting to look into format-directed printing
> Clean up tree rendering with a context struct

- src/byte_set.rs
- src/main.rs
This fixes all clippy lint warnings. To reduce annoyance I selectively disabled the redundant clone warnings when constructing the formats, and in the tests.
> Fix clippy lints

- src/lib.rs
- src/output/tree.rs
Expr is more powerful than Func and in fact can even replace `Func::U16Be` and more. This `MapExpr` format could almost replace `Map` entirely (aside from `Func::Stream`), however it currently does not print out names correctly as it pushes another item on the stack that the output tree does not know about. How to fix this?
> Format::MapExpr

- src/bin/doodle/format.rs
- src/bin/doodle/format/base.rs
- src/bin/doodle/format/jpeg.rs
- src/bin/doodle/format/tiff.rs
- src/lib.rs
- src/output/tree.rs
- tests/expected/decode/test.jpg.stdout
- tests/expected/decode/test2.jpg.stdout
Building off #54, this moves the `Func` operations into `Expr`, meaning we no longer need two map formats.
> Combine the functionality of map formats

- README.md
- frontend/.gitignore
- frontend/display.js
- src/bin/doodle/format.rs
- src/bin/doodle/main.rs
- src/byte_set.rs
- src/lib.rs
- tests/decode.rs
This implements `doodle format --output=json` for dumping the main format to stdout.
> Allow formats to be serialised to JSON

- src/lib.rs
- src/output/tree.rs
Intended for reading sequences of items until a condition is satisfied by the last item, for example a sequence of blocks where the last block has "final = true".
> Format::RepeatUntil.

- src/output/tree.rs
This handles the possibility of multiple projections in map formats
> Do a better job of recovering mapped formats

- src/lib.rs
> Decoder should immediately stop if match tree fails.

- src/bin/doodle/main.rs
- src/lib.rs
- src/output/tree.rs
`Format::Align(n)` will skip over (read and discard) the minimum number of bytes needed to ensure that the current offset is an integer multiple of `n`.
> Format for alignment

- src/bin/doodle/format/deflate.rs
- src/lib.rs
- src/output/tree.rs
UnwrapVariant was a hack anyway and impossible to type correctly, it should have used pattern matching.
> Remove Expr::UnwrapVariant and simplify some expr types

- src/lib.rs
- src/output/tree.rs
Adds `Expr` primitives for the Divide and Right-Shift operations, with support for pretty-printing said operations.
Clarifies documentation of `Format::Slice` to indicate its actual behavior under the current implementation (i.e. skip any leftover bytes within the slice after consuming as many bytes as the wrapped Format can allow it to).
> Add Expr::Div and Expr::Shr

- src/bin/doodle/main.rs
- src/output.rs
- src/output/flat.rs
- src/output/tree.rs
Introduces a parallel model for Pretty-Printing in the Tree-style, using a Writer-free `MonoidalPrinter` that builds text `Fragments` using structural induction. This model also uses precedence-based rules for parenthesizing expressions and formats.
WIP because this has not been tested rigorously enough, and because there is not yet a clean baton-pass from the previous `Context` model to `MonoidalPrinter`.
> Monoidal printing model with precedence rules

- src/bin/doodle/format.rs
- src/bin/doodle/format/tar.rs
- src/lib.rs
- src/output/flat.rs
- src/output/tree.rs
The simplest possible approach: it tries to parse each branch and takes the first one that succeeds. This will do exactly what we want for the one place where we currently use it: to distinguish between top-level file formats.
A smarter approach would be to run the branches in parallel and take the branch that proceeds the furthest without hitting an error, and to eliminate impossible branches earlier using a partial match tree, but that can wait.
> Nondeterministic unions

- src/bin/doodle/format/tar.rs
- src/output/tree.rs
- tests/expected/decode/test.gif.stdout
- tests/expected/decode/test.png.stdout
- tests/expected/decode/test.webp.stdout
Fixes various minor nits in the tar format definition, adjusts pretty-printing rules to handle more combinatorial Formats as ASCII string/characters, and similarly to treat more combinatorial Formats as "implied values" (i.e. can be omitted from tree printing)
> Fixes for tar, pretty-printing

- src/bin/doodle/format/base.rs
- src/bin/doodle/format/tar.rs
- src/byte_set.rs
- Adds `repeat_byte` format helper function to `base.rs` when a particular byte is repeated a fixed number of times.
- Adds `VALID_ASCII : ByteSet` const value for future use
- Fixes off-by-one in offset comments of tar header
- Adds `#[inline]` attributes, const modifiers to selected ByteSet functions (particularly, so that `from_bits`, `empty`, and `full` can be used in `const` declarations)
- Adds optimized `From<RangeInclusive<u8>>` for ByteSet, as well as `From<&' [u8]>` and `FromIterator<u8>`.
> Assorted tweaks to `base.rs` and ByteSet

- src/lib.rs
- src/output/flat.rs
- src/output/tree.rs
- tests/expected/decode/test1.gz.stdout
- tests/expected/decode/test2.gz.stdout
- tests/expected/decode/test3.gz.stdout
- tests/expected/decode/test4.gz.stdout
- tests/expected/decode/test5.gz.stdout
This implements unions where all the branches have the same type, either because they match the same structure (for example three bytes in UTF-8) or because they match records with the same type for the `@value` field. Such unions can return the value directly without the need to wrap it in a variant for each branch.
> Format::IsoUnion

- src/error.rs
- src/lib.rs
- src/output/flat.rs
- src/output/tree.rs
Create a child scope when you need one and simply discard it when done, this makes scope handling much more robust, without the risk of an early exit leaving the parent scope in an inconsistent state.
> Immutable scopes

- src/bin/doodle/format.rs
- src/bin/doodle/format/base.rs
- src/bin/doodle/format/jpeg.rs
- src/bin/doodle/format/utf8.rs
- src/lib.rs
- src/output/flat.rs
- src/output/tree.rs
This value is semantically transparent and only exists to trace the path of execution that created it, however it may be necessary for display purposes, to ensure we know the correct format.
> Value::Branch, to remember the branch taken in union and match formats

- src/output.rs
- src/output/tree.rs
Adds methods to `output::Fragment`, with the expectation that they might soon be useful, even if not currently used anywhere.
Improves documentation of Fragment type.
Minor fix to comments on `tree::Relation` enum variants.
> General improvements to Fragment type

- src/decoder.rs
- src/error.rs
This changes ScopeIter so it doesn't clone the scope it iterates over and also reverses the direction of iteration and recurses into parent scopes, so innermost bindings will be returned first.
> ScopeIter changes

- src/bin/doodle/format/gif.rs
- src/byte_set.rs
- src/decoder.rs
- src/lib.rs
- src/output.rs
- src/output/tree.rs
Initial attempt at documenting undocumented items in the `MatchTree*` family, along with some minor reordering of items and blocks in `lib.rs`.
Also includes a number of disparate changes based on `clippy` suggestions.
> Refactoring, documentation, and clippy-informed cleanup

- src/output/tree.rs
Performs a very easy, but overlooked refactoring in `tree.rs`
> Use existing type-alias to simplify signatures

- src/bin/doodle/format/deflate.rs
- src/decoder.rs
- src/error.rs
- src/lib.rs
- src/output/flat.rs
- src/output/tree.rs
- tests/expected/decode/test1.gz.stdout
- tests/expected/decode/test2.gz.stdout
- tests/expected/decode/test3.gz.stdout
- tests/expected/decode/test4.gz.stdout
- tests/expected/decode/test5.gz.stdout
This improves on #121 by adding as simple kind system that separates format types from value types.
Expression evaluation can only return a value type, not a format type. In particular variables can only evaluate to values, not formats. This makes it impossible to put a format in a record or a tuple or pattern match on formats or anything like that.
Let bindings work for value types, `let name := expr in format` behaves as you would expect.
Dynamic bindings compile a dynamic format: `dynamic name := format in format` will compile the specified dynamic format to a decoder that can be applied by name.
Compiled decoders live in the scope, stored in a ScopeEntry that is either a value or a decoder.
As far as I can tell this scheme is sound and seems a lot easier to prove that it's sound.
> Let bindings, separate kinds for values and formats

- src/bin/doodle/format/base.rs
- src/decoder.rs
- src/error.rs
- src/etc.rs
- src/lib.rs
- src/output.rs
- src/output/flat.rs
- src/output/tree.rs
Many sites within `lib.rs` and modules that extend or rely on related API details currently have `Cow<'static, str>` as a stand-in for `String`. This PR simply aliases the majority of such instances that share the same semantic intent as `etc::Label`, where `Label` is a simple type-alias defined in a new `etc.rs` submodule of `lib.rs`.
This is more of a stylistic change than anything and can easily be skipped if there is there is no compelling reason to adopt this alias.
> Introduce Label alias for Cow<'static, str> in lib

- DESIGN.md
- src/lib.rs
Additionally, removes an unconditionally `Ok()` `Result` type from `MatchTreeLevel::merge_branch`.
EDIT:
Also adds a new document, `DESIGN.md`, for the purposes of externally documenting the `MatchTree*` family of types and the model they present.
> Renaming, documenting of methods and items in the MatchTree* family

- src/bin/doodle/format/base.rs
- src/decoder.rs
- src/lib.rs
- src/output/tree.rs
The main reason to coalesce all the relational and arithmetic expressions is that they all have the same type, so it avoids some tedious code duplication when experimenting with different approaches to type checking.
> Simplify Expr type by introducing Arith and IntRel enums.

- src/bin/doodle/format.rs
- src/bin/doodle/format/base.rs
- src/bin/doodle/format/text.rs
- src/decoder.rs
- src/lib.rs
- src/output/flat.rs
- src/output/tree.rs
This change shifts the variant label syntax sugar to a helper function, which simplifies the core format language.
> Change Format::UnionNondet to be consistent with Union.

- src/codegen/typed_decoder.rs
- src/codegen/typed_format.rs
- src/decoder.rs
- src/lib.rs
Adds `Format` and `TypedFormat` methods `lookahead_bounds` that mirrors `match_bounds`, but returns the expected limits on bytes read, regardless of how many are consumed.
> Add lookahead_bounds method

- codegen_tests.rs
- sample_codegen.rs
- src/bin/doodle/format.rs
- src/bin/doodle/format/png.rs
- src/byte_set.rs
- src/codegen/mod.rs
- src/codegen/rust_ast.rs
- src/codegen/typed_format.rs
- src/decoder.rs
- src/helper.rs
- src/lib.rs
- src/parser/error.rs
- src/parser/mod.rs
- src/parser/offset.rs
- src/precedence.rs
Gets rid of the `#![allow(dead_code)]` attribute at the root of `rust_ast.rs` to surface unused variants and methods (and removes them).
Fixes many proper typos in comments, and changes identifiers in certain places to keep spellchecking simple.
Basic heuristics to selectively elide vacuous expressions like
```rust
let _ = ();
```
from generated code by determining, using a loose heuristic, whether any given `RustExpr` is 'pure' in the Haskell sense. 
Promotes any hard-coded strings leftover in `rust_ast.rs` or `codegen/mod.rs` that inject 'extra' content into standard productions, into associated fields of the types being augmented, which are then expanded as first-class elements of the Rust-AST model rather than hacky afterthoughts.
> Static analysis for selective elision of vacuous expressions, promotion of hard-coded strings to productive elements of associated model-structures

- doodle-formats/src/format/png.rs
- generated/codegen_tests.rs
- generated/sample_codegen.rs
- src/codegen/mod.rs
- src/codegen/typed_decoder.rs
- src/codegen/typed_format.rs
- src/decoder.rs
- src/disjoint.rs
- src/helper.rs
- src/lib.rs
- src/loc_decoder.rs
- src/output/flat.rs
- src/output/tree.rs
- src/parser/error.rs
- src/typecheck.rs
Downstream changes to #177 including codegen support and application of new helper `where_lambda` to PNG iCCP validation (rather than hardcoding `:= 0` at the syntax-level)
> Extend codegen support to Format::Where

- doodle-formats/src/format.rs
- src/decoder.rs
- src/error.rs
- src/loc_decoder.rs
We currently have two types called `ParseError`:
- [doodle::error::ParseError](https://github.com/yeslogic/doodle/blob/6d46d76af3e60387a8dec5321585920f342a31f1/src/error.rs#L11)
- [doodle::parser::error::ParseError](https://github.com/yeslogic/doodle/blob/6d46d76af3e60387a8dec5321585920f342a31f1/src/parser/error.rs#L5)
This PR changes the naming conventions of the former to use `Decode` as the action-verb instead of `Parse`, in all sites that define the type itself or its derived/variant relatives.
> Renames interpreter-based `ParseError`/`ParseResult` to avoid shadowing other definition using same name

- doodle-formats/src/format/png.rs
- generated/api_helper/otf_metrics.rs
- generated/codegen_tests.rs
- generated/gencode.rs
- src/codegen/mod.rs
- src/helper.rs
(Includes commits from #238)
Removes `Format::Record` entirely, and introduces two new `Format` variants to serve for record-construction purposes:
- `MonadSeq`: Variation of `LetFormat` that explicitly discards one parse and yields the result of the other (i.e. without binding to a variable)
- `Hint`: Used to associate a particular informational bread-crumb with a `Format` node, so that deep introspection and complex heuristics are not needed to identify the meta-structural properties of a `Format`. Currently used to wrap the first bind-or-sequence of a Record construction, so that it can be identified as being Record-style far more simply.
This shift introduces a slight distinction to Record-kinded parses, between **old-style** and **new-style**:
Old-style records bind (and persist, at …
> Redesign syntactical conventions for specifying `Record`-kinded parses

- generated/gencode.rs
- src/codegen/mod.rs
Prevents generation of `(|| DecoderXYZZY(_input))()?` one-liners where closure is constructed and immediately called without any difference in behavior.
> Fix `local_try` to only generate closures if stmts short-circuit

- doodle-formats/src/format/opentype.rs
- generated/api_helper/otf_metrics.rs
- generated/gencode.rs
- src/bounds.rs
Updated so that it is no longer floating, and should be possible to directly merge onto main
> Opentype ItemVariationStore implementation

- doodle-formats/src/format/png.rs
- generated/gencode.rs
- src/codegen/mod.rs
- src/codegen/rust_ast/mod.rs
- src/codegen/rust_ast/rebind.rs
- src/codegen/rust_ast/resolve.rs
- src/codegen/typed_decoder.rs
- src/codegen/typed_format.rs
- src/decoder.rs
- src/decoder/seq_kind.rs
- src/helper.rs
- src/lib.rs
- src/loc_decoder.rs
- src/output/flat.rs
- src/output/tree.rs
- src/precedence.rs
- src/prelude.rs
- src/typecheck.rs
- tests/expected/decode/test.png.stdout
Adds `Format::Sequence`, which is effectively a restricted form of `Format::Tuple` for parses of the same type, which returns them in a `Seq` container rather than an N-tuple.
> Add Format::Sequence, Expr::Append for Sequence QoL
